[project]
name = "aliceblue-mcp"
version = "0.1.0"
description = "AliceBlue Trading MCP Server"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp",
    "fastmcp",
    "smithery",
    "requests",
]

[tool.smithery]
server = "aliceblue_server.server:create_server"

[tool.smithery.dev]
command = "uvicorn aliceblue_server.server:create_server --port 8000 --reload"

[tool.smithery.playground]
command = "uvicorn aliceblue_server.server:create_server --port 8000"