name: Deploy to Smithery

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Validate smithery.yaml
        run: |
          if [ ! -f "smithery.yaml" ]; then
            echo "❌ smithery.yaml file is missing!"
            exit 1
          fi
          echo "✅ smithery.yaml found"
          
      - name: Test server startup
        run: |
          timeout 10s python server.py || exit 0
          echo "✅ Server imports successfully"
          
      - name: Deploy to Smithery
        uses: smithery-ai/deploy-action@v1
        with:
          smithery-token: ${{ secrets.SMITHERY_TOKEN }}