name: Deploy to Smithery

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          
      - name: Validate build files
        run: |
          if [ ! -f "pyproject.toml" ]; then
            echo "❌ pyproject.toml file is missing!"
            exit 1
          fi
          if [ ! -f "smithery.yaml" ]; then
            echo "❌ smithery.yaml file is missing!"
            exit 1
          fi
          echo "✅ All required build files found"
          
      - name: Test server startup
        run: |
          timeout 10s python -c "import server; print('✅ Server imports successfully')" || exit 0
          
      - name: Deploy to Smithery
        uses: smithery-ai/deploy-action@v1
        with:
          smithery-token: ${{ secrets.SMITHERY_TOKEN }}